Dr 43 wcs user management
weaviate/weaviate-io pull request #2146
Opened 2024-05-28 19:10 UTC by daveatweaviate

[issue](https://semi-technology.atlassian.net/browse/DR-43)
[staging](https://dr-43-wcs-user-management--tangerine-buttercream-20c32f.netlify.app/developers/wcs/platform/users-and-organizations)

2024-05-28 19:15 UTC, daveatweaviate commented
Hi @harrlight00  this is an overview of how users and orgs work in WCS. Would you take a look when you get a moment?

2024-05-29 21:16 UTC, harrlight00 requested changes

2024-05-29 21:16 UTC, harrlight00 commented on developers/wcs/platform/users-and-organizations.mdx
> +:::note Cluster restart
If a cluster is past a certain version, adding or removing a user will not restart the cluster. I do not remember which version though, whichever version added groups

2024-05-29 21:16 UTC, harrlight00 commented on developers/wcs/platform/users-and-organizations.mdx
> +Each cycle the account gets a bill that includes charges for all of the clusters. The charges are itemized by cluster, not by user.
The account will get a stand alone invoice for each cluster, on a 30 day cycle from when each cluster was created

2024-05-29 21:52 UTC, harrlight00 approved these changes

2024-05-29 22:08 UTC, merged