DR-457 compression overview
weaviate/weaviate-io pull request #2241
Opened 2024-06-24 19:40 UTC by daveatweaviate

[issue](https://semi-technology.atlassian.net/browse/DR-457)
[staging]()

2024-08-07 03:10 UTC, daveatweaviate commented
@sebawita would you have a look at this draft when you get a moment? Thanks!

2024-08-07 16:18 UTC, sebawita requested changes

2024-08-07 16:18 UTC, sebawita commented on developers/weaviate/starter-guides/compression.mdx
> +- PQ indexes have response rates approach the response rates of uncompressed indexes when recall reaches 97 percent and higher. At those levels of recall, the [speed profile](/blog/pq-rescoring#qps-v
> Both indexes handle about 200 queries per second (QPS).

The 200 QPS depends on the data and server spec.
We should remove this sentence.

2024-08-07 16:18 UTC, sebawita commented on developers/weaviate/starter-guides/compression.mdx
> +- PQ indexes have response rates approach the response rates of uncompressed indexes when recall reaches 97 percent and higher. At those levels of recall, the [speed profile](/blog/pq-rescoring#qps-v
We can include benchmarks later. But these will have specific params

2024-08-07 16:18 UTC, sebawita commented on developers/weaviate/starter-guides/compression.mdx
> +Importing and compressing vectors takes slightly longer than just importing them, but this is a one time cost. In contrast, loading a compressed index into memory is faster since there is less data t
> Importing and compressing vectors takes slightly longer than just importing them,

Maybe we could say: "than importing uncompressed vectors" 🤔

2024-08-07 16:18 UTC, sebawita commented on developers/weaviate/starter-guides/compression.mdx
> +Starting in v1.22, Weaviate has an optional, [asynchronous indexing](/developers/weaviate/config-refs/schema/vector-index#asynchronous-indexing) feature which improves the import process. When asynch
Hmmm... I am not sure if this is helpful in the context of compression. 🤔

2024-08-07 16:18 UTC, sebawita commented on developers/weaviate/starter-guides/compression.mdx
> +- The cost savings are significant. In [Weaviate Cloud](https://weaviate.io/pricing), for example, uncompressed collections can be 5 to 8 times as expensive as compressed collections.
Let's focus this sentence on the positive side and say that compressed collections can yield xyz savings! (not necessarily in these words)

2024-08-07 16:18 UTC, sebawita commented on developers/weaviate/starter-guides/compression.mdx
> +### Documentation pages
Let's add something here to say that you can go to these pages to learn how to configure/enable these compressions

2024-08-07 16:18 UTC, sebawita commented on developers/weaviate/starter-guides/compression.mdx
> +For additional details, refer to the [blog posts](#blog-posts).
hmmm... I am not sure if this adds much at this point.
Maybe this sentence could be added at the start of the blog post segment 🤔

2024-08-08 17:32 UTC, daveatweaviate reviewed
@sebawita thanks for your feedback this is ready for another pass

2024-08-13 09:45 UTC, trengrj commented on developers/weaviate/starter-guides/compression.mdx
> +- Most users with medium to large data sets should consider SQ compression. SQ compressed vectors are one quarter the size of uncompressed vectors. Searches with SQ are several times faster than sear
Searches with SQ are several times faster than searches with uncompressed vectors -> Searches with SQ are faster than searches with uncompressed vectors

2024-08-13 15:28 UTC, daveatweaviate reviewed
@trengrj thanks for your feedback 

I've updated the copy here and sent a note to Sebastian in the channel about the other comments.

2024-08-13 15:28 UTC, daveatweaviate commented on developers/weaviate/starter-guides/compression.mdx
> +- Most users with medium to large data sets should consider SQ compression. SQ compressed vectors are one quarter the size of uncompressed vectors. Searches with SQ are several times faster than sear
Updated, thanks!

2024-08-15 18:14 UTC, merged