Add search filters examples
weaviate/weaviate-io pull request #2495
Opened 2024-08-27 18:29 UTC by donomii

### What's being changed:

### Type of change:

- [ ] **Documentation** updates (non-breaking change to fix/update documentation)
- [ ] **Website** updates (non-breaking change to update main page, company pages, pricing, etc)
- [ ] **Content** updates – **blog**, **podcast** (non-breaking change to add/update content)
- [ ] **Bug fix** (non-breaking change to fixes an issue with the site)
- [ ] **Feature** or **enhancements** (non-breaking change to add functionality)

### How Has This Been Tested?

- [ ] **GitHub action** – automated build completed without errors
- [ ] **Local build** - the site works as expected when running `yarn start`

> note, you can run `yarn verify-links` to test site links locally

2024-08-28 21:23 UTC, daveatweaviate reviewed
Thanks @donomii this is a huge help

I left a couple of comments here after testing the code. Let me know if you have any questions.

There's also a comment in our slack DM about the nested filter operands. (the points can't be greater than 700 and less than 300 at the same time)

2024-08-28 21:23 UTC, daveatweaviate commented on _includes/code/howto/go/docs/mainpkg/search-filters_test.go
> +			graphql.Field{Name: "question"},
I think the field name should be "title"

2024-08-28 21:23 UTC, daveatweaviate commented on _includes/code/howto/go/docs/mainpkg/search-filters_test.go
> +			graphql.Field{Name: "question"},
This line shouldn't be here, Articles doesn't have a question field

2024-08-29 05:52 UTC, antas-marcin approved these changes

2024-08-29 05:54 UTC, antas-marcin requested changes
I think we need to fix the indentation bc the Go examples are not properly indented

2024-09-03 22:09 UTC, daveatweaviate commented
@antas-marcin  - I think GitHub wants you to approve the indent changes. Would you have a look? 

Thanks!

2024-09-04 10:07 UTC, antas-marcin commented
@daveatweaviate the indentation is now correct, but we lost Go code syntax highlighting (look [here](https://search-filters-go--tangerine-buttercream-20c32f.netlify.app/developers/weaviate/search/filters#filter-with-multiple-conditions))

2024-09-04 13:18 UTC, donomii commented
> @daveatweaviate the indentation is now correct, but we lost Go code syntax highlighting (look [here](https://search-filters-go--tangerine-buttercream-20c32f.netlify.app/developers/weaviate/search/filters#filter-with-multiple-conditions))

Working on this now

2024-09-04 13:41 UTC, antas-marcin approved these changes

2024-09-04 14:35 UTC, merged