Fix typos and resolve open todos
weaviate/weaviate-io pull request #972
Opened 2023-07-13 10:26 UTC by iamleonie

### What's being changed:

### Type of change:

- [x] **Documentation** updates (non-breaking change to fix/update documentation)
- [ ] **Website** updates (non-breaking change to update main page, company pages, pricing, etc)
- [ ] **Content** updates – **blog**, **podcast** (non-breaking change to add/update content)
- [ ] **Bug fix** (non-breaking change to fixes an issue with the site)
- [ ] **Feature** or **enhancements** (non-breaking change to add functionality)

### How Has This Been Tested?

- [ ] **Github action** – automated build completed without errors
- [x] **Local build** - the site works as expected when running `yarn start`

> note, you can run `yarn verify-links` to test site links locally

2023-07-13 10:28 UTC, iamleonie commented on developers/academy/zero_to_mvp/103_schema_and_imports/30_import.mdx
> -:::warning TODO
This is just a suggestion: I don't think an example code snippet is necessary here. The tutorial flows well without it and thus I would clean this up by simply removing this TODO field.

2023-07-13 22:39 UTC, databyjp commented on developers/academy/zero_to_mvp/103_schema_and_imports/40_example.mdx
> +  endMarker='# Finished creating the class'
Hey, this is to pull up a code snippet based on these markers. So we can change these, but we'll have to change the corresponding comment in the code. :) 

I propose to leave this one as is for now.

2023-07-13 22:41 UTC, databyjp commented on developers/academy/zero_to_mvp/104_queries_2/20_hybrid.mdx
> +This can produce helpful results when a vector search or a keyword search alone is not producing desired results. For example, it may be useful when a vector search alone is producing too many irrele
I think "weight" is correct here as it's describing like scaling one of vector or bm25 results more heavily than the other.

2023-07-13 22:43 UTC, databyjp requested changes
Hi Leonie, thanks so much for these! :) 

Would you mind making those small changes? And then we can merge the PR.

2023-07-17 09:11 UTC, databyjp commented on developers/academy/zero_to_mvp/103_schema_and_imports/40_example.mdx
> +  endMarker='# Finished creating the class'
Oh my bad ;) I see that also comes from the code :)

2023-07-17 12:25 UTC, merged